server:
  port: 8103
spring:
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 0.1  #设置Sleuth的抽样收集概率
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8004/eureka/