server:
  port: 8308
spring:
  #开启服务请求链路跟踪，通过zipkin-server（无需我们搭建，网上下载运行即可），可
  #查看访问在各个服务跳转情况，再结合Elasticsearch将日志保存下来（zipkin-server只能存在内存中），通过kibana查看
  #Elasticsearch所保存下来的信息以供我们找到问题所对应的具体服务
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1  #设置Sleuth的抽样收集概率
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8004/eureka/
service-url:
  user-service: http://eureka-client
