server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitee.com/lin-zhaojia/homepage.git
          username: lin-zhaojia
          password: 159189lzj+
          clone-on-start: true #开启启动时直接从git获取配置
#          search-paths: '{application}'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8004/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'